name: coronavirus
channels:
  - simplistix
  - pyviz
  - conda-forge
dependencies:
  - bokeh > 2.3
  - ffmpeg
  - geopandas >= 0.9
  - imageio
  - imagemagick
  - jupyter >= 1.0.0
  - matplotlib > 3.4.0
  - moviepy > 1.0
  - openpyxl
  - pandas > 1.2
  - pip > 21.1
  - picky-conda
  - pyproj > 2.6 # otherwise the solver picks an older version that doesn't work!
  - python=3.8
  - python-dateutil >= 2.8
  - scipy > 1.6
  - shapely
  - tqdm
  - pip:
    - mpl-axes-aligner
    - pygifsicle

